# Generated by Django 5.1.4 on 2024-12-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("price", models.DecimalField(decimal_places=0, max_digits=10)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
