# Generated by Django 5.1.4 on 2024-12-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0003_delete_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=12)),
                ("message", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
    ]
