# Generated by Django 5.1.4 on 2025-02-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0005_order"),
    ]

    operations = [
        migrations.DeleteModel(name="Order",),
    ]
