# Generated by Django 5.1.4 on 2025-02-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0006_delete_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=255)),
                ("address2", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=20)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("credit", "Credit Card"),
                            ("debit", "Debit Card"),
                            ("paypal", "PayPal"),
                        ],
                        default="credit",
                        max_length=10,
                    ),
                ),
                ("cc_name", models.CharField(blank=True, max_length=100, null=True)),
                ("cc_number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "cc_expiration",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("cc_cvv", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "paypal_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("debit_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "debit_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "debit_expiration",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("debit_cvv", models.CharField(blank=True, max_length=4, null=True)),
                ("same_address", models.BooleanField(default=False)),
                ("save_info", models.BooleanField(default=False)),
                ("agreed_to_terms", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
