# Generated by Django 5.1.4 on 2025-02-08 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0007_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="email", new_name="email_address",
        ),
        migrations.RenameField(
            model_name="order", old_name="phone", new_name="phone_number",
        ),
        migrations.RemoveField(model_name="order", name="address2",),
    ]
