# Generated by Django 5.1.4 on 2025-02-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0008_rename_email_order_email_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cart_items",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.CharField(default="pending", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(
                choices=[
                    ("US", "United States"),
                    ("CA", "Canada"),
                    ("GB", "United Kingdom"),
                    ("IN", "India"),
                    ("AU", "Australia"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(
                choices=[
                    ("CA", "California"),
                    ("NY", "New York"),
                    ("TX", "Texas"),
                    ("FL", "Florida"),
                    ("IL", "Illinois"),
                ],
                max_length=2,
            ),
        ),
    ]
