# Generated by Django 5.1.4 on 2025-02-10 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0009_order_cart_items_order_order_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="cart_items",),
        migrations.RemoveField(model_name="order", name="order_status",),
        migrations.RemoveField(model_name="order", name="total_price",),
    ]
