# Generated by Django 5.1.4 on 2025-02-11 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0011_orderitem"),
    ]

    operations = [
        migrations.DeleteModel(name="OrderItem",),
    ]
