# Generated by Django 5.1.4 on 2025-02-21 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0012_delete_orderitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="address",),
        migrations.RemoveField(model_name="order", name="agreed_to_terms",),
        migrations.RemoveField(model_name="order", name="cc_cvv",),
        migrations.RemoveField(model_name="order", name="cc_expiration",),
        migrations.RemoveField(model_name="order", name="cc_name",),
        migrations.RemoveField(model_name="order", name="cc_number",),
        migrations.RemoveField(model_name="order", name="country",),
        migrations.RemoveField(model_name="order", name="debit_cvv",),
        migrations.RemoveField(model_name="order", name="debit_expiration",),
        migrations.RemoveField(model_name="order", name="debit_name",),
        migrations.RemoveField(model_name="order", name="debit_number",),
        migrations.RemoveField(model_name="order", name="email_address",),
        migrations.RemoveField(model_name="order", name="first_name",),
        migrations.RemoveField(model_name="order", name="last_name",),
        migrations.RemoveField(model_name="order", name="payment_method",),
        migrations.RemoveField(model_name="order", name="paypal_email",),
        migrations.RemoveField(model_name="order", name="phone_number",),
        migrations.RemoveField(model_name="order", name="same_address",),
        migrations.RemoveField(model_name="order", name="save_info",),
        migrations.RemoveField(model_name="order", name="state",),
        migrations.RemoveField(model_name="order", name="zip_code",),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ShippingDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                ("shipping_method", models.CharField(max_length=100)),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shipping_status",
                    models.CharField(
                        choices=[
                            ("not_shipped", "Not Shipped"),
                            ("shipped", "Shipped"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                        ],
                        default="not_shipped",
                        max_length=50,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_details",
                        to="Home.order",
                    ),
                ),
            ],
        ),
    ]
