# Generated by Django 5.1.4 on 2025-02-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0013_remove_order_address_remove_order_agreed_to_terms_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="status",),
        migrations.RemoveField(model_name="order", name="total_price",),
        migrations.RemoveField(model_name="order", name="user",),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.CharField(default="Default Address", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="agreed_to_terms",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="cc_cvv",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="cc_expiration",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="cc_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="cc_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(default="Default Country", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="debit_cvv",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="debit_expiration",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="debit_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="debit_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="email_address",
            field=models.EmailField(default="default@example.com", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="first_name",
            field=models.CharField(default="Default First Name", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="last_name",
            field=models.CharField(default="Default Last Name", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit", "Credit Card"),
                    ("debit", "Debit Card"),
                    ("paypal", "PayPal"),
                ],
                default="credit",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="paypal_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(default="000-000-0000", max_length=15),
        ),
        migrations.AddField(
            model_name="order",
            name="same_address",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="save_info",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="state",
            field=models.CharField(
                choices=[
                    ("CA", "California"),
                    ("NY", "New York"),
                    ("TX", "Texas"),
                    ("FL", "Florida"),
                    ("IL", "Illinois"),
                ],
                default="Default State",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="zip_code",
            field=models.CharField(default="00000", max_length=20),
        ),
        migrations.DeleteModel(name="ShippingDetails",),
    ]
