# Generated by Django 5.1.4 on 2025-02-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0014_remove_order_status_remove_order_total_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(default=" ", max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(
                choices=[
                    ("", "Select"),
                    ("US", "United States"),
                    ("CA", "Canada"),
                    ("GB", "United Kingdom"),
                    ("IN", "India"),
                    ("AU", "Australia"),
                ],
                default=" ",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="email_address",
            field=models.EmailField(default=" ", max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(default=" ", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(default=" ", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(default=" ", max_length=15),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(
                choices=[
                    ("", "Select"),
                    ("CA", "California"),
                    ("NY", "New York"),
                    ("TX", "Texas"),
                    ("FL", "Florida"),
                    ("IL", "Illinois"),
                ],
                default=" ",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="zip_code",
            field=models.CharField(default=" ", max_length=20),
        ),
    ]
