# Generated by Django 5.1.4 on 2025-02-21 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0015_alter_order_address_alter_order_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(
                choices=[
                    ("US", "United States"),
                    ("CA", "Canada"),
                    ("GB", "United Kingdom"),
                    ("IN", "India"),
                    ("AU", "Australia"),
                ],
                default=" ",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(
                choices=[
                    ("CA", "California"),
                    ("NY", "New York"),
                    ("TX", "Texas"),
                    ("FL", "Florida"),
                    ("IL", "Illinois"),
                ],
                default=" ",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="zip_code",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="Home.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Home.product"
                    ),
                ),
            ],
        ),
    ]
