# Generated by Django 5.1.4 on 2025-02-22 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0017_customer_delete_orderitem"),
    ]

    operations = [
        migrations.DeleteModel(name="Customer",),
    ]
