# Generated by Django 5.1.4 on 2025-02-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0019_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
