# Generated by Django 5.1.4 on 2025-02-22 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0020_customer_address_customer_phone_number"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="user",),
    ]
