# Generated by Django 5.1.4 on 2025-02-22 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0021_remove_customer_user"),
    ]

    operations = [
        migrations.DeleteModel(name="Customer",),
    ]
