# Generated by Django 5.1.4 on 2025-02-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0022_delete_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(to="Home.product"),
        ),
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
