# Generated by Django 5.1.4 on 2025-02-27 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0023_order_products_order_total_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="first_name", new_name="full_name",
        ),
        migrations.RemoveField(model_name="order", name="last_name",),
    ]
