# Generated by Django 5.1.4 on 2025-02-27 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0025_order_order_status_orderitem"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="products",),
    ]
