# Generated by Django 5.1.4 on 2025-02-27 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0026_remove_order_products"),
    ]

    operations = [
        migrations.DeleteModel(name="OrderItem",),
    ]
