# Generated by Django 5.1.6 on 2025-02-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0027_delete_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cart_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
