# Generated by Django 5.1.6 on 2025-02-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0029_alter_order_cart_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cart_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
