# Generated by Django 5.1.6 on 2025-02-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0032_alter_order_cart_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="orders", to="Home.product"
            ),
        ),
    ]
