# Generated by Django 5.1.6 on 2025-03-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0033_order_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("US", "United States"),
                    ("CA", "Canada"),
                    ("GB", "United Kingdom"),
                    ("IN", "India"),
                    ("AU", "Australia"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="email_address",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="full_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CA", "California"),
                    ("NY", "New York"),
                    ("TX", "Texas"),
                    ("FL", "Florida"),
                    ("IL", "Illinois"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
