# Generated by Django 5.1.4 on 2025-04-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0034_alter_order_address_alter_order_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cart_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
