# Generated by Django 5.1.4 on 2025-04-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0035_alter_order_cart_data"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="cc_cvv",),
        migrations.RemoveField(model_name="order", name="cc_expiration",),
        migrations.RemoveField(model_name="order", name="cc_name",),
        migrations.RemoveField(model_name="order", name="cc_number",),
        migrations.RemoveField(model_name="order", name="debit_cvv",),
        migrations.RemoveField(model_name="order", name="debit_expiration",),
        migrations.RemoveField(model_name="order", name="debit_name",),
        migrations.RemoveField(model_name="order", name="debit_number",),
        migrations.RemoveField(model_name="order", name="payment_method",),
        migrations.RemoveField(model_name="order", name="paypal_email",),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="product", name="price", field=models.FloatField(),
        ),
    ]
